#!/usr/bin/env bash
set -euo pipefail

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [ -z "${DEV_ENV:-}" ]; then
    echo "You must run this with DEV_ENV set, like:"
    echo "    DEV_ENV=\$PWD ./run"
    exit 1
fi

export DEV_ENV="$DEV_ENV"

grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    else
        grep="$1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN] $1"
    else
        echo "$1"
    fi
}

log "Running setup from $DEV_ENV..."

runs=$(find "$script_dir/runs" -mindepth 1 -maxdepth 1 -executable | sort)

for s in $runs; do
    if basename "$s" | grep -vq "$grep"; then
        log "Skipping (filtered out): $s"
        continue
    fi

    log "Running: $s"
    if [[ $dry_run == "0" ]]; then
        "$s"
    fi
done
