#!/usr/bin/env bash

set -e

echo "Installing dev packages..."

sudo pacman -S \
  grim \
  slurp \
  vivaldi \
  cliphist \
  wl-clipboard \
  wl-clip-persist \
  hyprpolkitagent \
  --noconfirm --needed

yay -S pyprland rose-pine-hyprcursor --noconfirm --needed

echo "dev packages installed successfully."
