---
include:
- "**/*.rb"
- "**/*.erb"
- "**/*.rake"
- "**/*.gemspec"
- "**/*.jbuilder"
- config/**/*.rb
exclude:
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require:
- actioncable
- actionmailer
- actionpack
- actionview
- activejob
- activemodel
- activerecord
- activestorage
- activesupport
domains: []
reporters:
- rubocop
- require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins:
- solargraph-rails
- solargraph-rspec
max_files: 0
