#!/usr/bin/env bash

TARGET_DIR=$(zoxide query -l | fzf --prompt="Pick a recent project: ")
[[ -z "$TARGET_DIR" ]] && exit 1

SESSION_NAME=$(basename "$TARGET_DIR")

if ! tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
  tmux new-session -d -s "$SESSION_NAME" -n vim -c "$TARGET_DIR" 'zsh -c "nvim .; exec zsh"'

  tmux new-window -t "$SESSION_NAME" -n scratch -c "$TARGET_DIR"
fi

FIRST_WIN=$(tmux list-windows -t "$SESSION_NAME" -F "#{window_index}" | sort -n | head -n 1)

if [ -n "$TMUX" ]; then
  tmux switch-client -t "$SESSION_NAME:$FIRST_WIN"
else
  tmux attach-session -t "$SESSION_NAME" \; select-window -t "$SESSION_NAME:$FIRST_WIN"
fi
