[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "foot --app-id foot-dropterm --title DropTerm"
class = "foot-dropterm"
size = "85% 70%"
max_size = "1920px 100%"
margin = 50
lazy = true
