alias c="clear"
alias vim="nvim"
alias vz="nvim ~/.zshrc"
alias sz="source ~/.zshrc && echo 'zshrc sourced'"

alias t="tmux"
alias td="tmux detach"
alias tp="tmux-project"

alias l="lsd -l --group-directories-first"
alias ls="lsd --group-directories-first"
alias la="lsd -a --group-directories-first"
alias lla="lsd -la --group-directories-first"
alias lt="lsd --tree --depth 2 --group-directories-first"
alias ltt="lsd --tree --group-directories-first"

alias rc="rails console"
alias rdd="rails db:drop"
alias rdc="rails db:create"
alias rdm="rails db:migrate"
alias rdmd="rails db:migrate:down"
alias rdmr="rails db:migrate:redo"
alias rdr="rails db:rollback"
alias rdrs="rails db:reset"
alias rds="rails db:seed"
alias rdt="rails db:truncate_all"
alias rgen="rails generate"
alias rgm="rails generate migration"
alias rs="rails server"
alias rsd="rails server --debugger"
alias rt="rspec"
